set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/fsmStateDDR[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/fsmStateDDR[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/fsmStateDDR[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/enqueueFSM[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/enqueueFSM_reg[1]_0}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/dequeueFSM[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/dequeueFSM[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/HarrisFSM[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/HarrisFSM[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/HarrisFSM[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/image_loaded_reg_n_3_[0]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/Block_codeRepl141_pr_U0/skip_read]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/img_in_axi_stream_V_1_fifo_U/write_chunk_to_ddr_p_reg[0]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/Block_codeRepl141_pr_U0/ready_to_accept_new_4_reg_1166]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/signal_init[0]_i_2_n_3}]
set_property MARK_DEBUG true [get_nets ROLE/soMemWrCmdP0_TVALID]
set_property MARK_DEBUG true [get_nets ROLE/UAF/soMemWrCmdP0_TREADY]
set_property MARK_DEBUG true [get_nets ROLE/siMemWrStsP0_TREADY]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[7]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/siMemWrStsP0_TVALID]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWriteP0_TLAST[0]}]
set_property MARK_DEBUG true [get_nets ROLE/soMemWriteP0_TVALID]
set_property MARK_DEBUG true [get_nets ROLE/UAF/soMemWriteP0_TREADY]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWriteP0_TKEEP[0]}]

set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[10]}]

set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[34]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[54]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[36]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[35]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[37]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[39]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[33]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[32]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[28]}]
set_property MARK_DEBUG true [get_nets ROLE/m_axi_moMEM_Mp1_AWVALID]
set_property MARK_DEBUG true [get_nets ROLE/m_axi_moMEM_Mp1_ARVALID]
set_property MARK_DEBUG true [get_nets ROLE/m_axi_moMEM_Mp1_BREADY]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_siROL_Mem_Mp0_Write_tready[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tvalid[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWSIZE[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_siROL_Mem_Mp0_WrCmd_tready[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[32]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_miROL_Mem_Mp1_WREADY[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_miROL_Mem_Mp1_RVALID[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[27]}]
set_property MARK_DEBUG true [get_nets ROLE/m_axi_moMEM_Mp1_RREADY]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[8]}]
set_property MARK_DEBUG true [get_nets ROLE/m_axi_moMEM_Mp1_WLAST]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[32]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWADDR[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_ARADDR[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWSIZE[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/m_axi_moMEM_Mp1_AWSIZE[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_miROL_Mem_Mp1_ARREADY[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/rp_ROLE_miROL_Mem_Mp1_AWREADY[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list SHELL/SuperCfg.ETH0/ETH/CORE/IP/inst/xpcs/inst/ten_gig_eth_pcs_pma_shared_clock_reset_block/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/HarrisFSM[0]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/HarrisFSM[1]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/HarrisFSM[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[0]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[1]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[2]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[3]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[4]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[5]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[6]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[7]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[8]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[9]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[10]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[11]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[12]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[13]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[14]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[15]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[16]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[17]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[18]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[19]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[20]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[21]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[22]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[23]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[24]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[25]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[26]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[27]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[28]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[29]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[30]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/dequeueFSM[0]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/dequeueFSM[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/enqueueFSM[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/fsmStateDDR[0]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/fsmStateDDR[1]} {ROLE/UAF/U0/Block_codeRepl141_pr_U0/fsmStateDDR[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 33 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {ROLE/m_axi_moMEM_Mp1_ARADDR[0]} {ROLE/m_axi_moMEM_Mp1_ARADDR[1]} {ROLE/m_axi_moMEM_Mp1_ARADDR[2]} {ROLE/m_axi_moMEM_Mp1_ARADDR[3]} {ROLE/m_axi_moMEM_Mp1_ARADDR[4]} {ROLE/m_axi_moMEM_Mp1_ARADDR[5]} {ROLE/m_axi_moMEM_Mp1_ARADDR[6]} {ROLE/m_axi_moMEM_Mp1_ARADDR[7]} {ROLE/m_axi_moMEM_Mp1_ARADDR[8]} {ROLE/m_axi_moMEM_Mp1_ARADDR[9]} {ROLE/m_axi_moMEM_Mp1_ARADDR[10]} {ROLE/m_axi_moMEM_Mp1_ARADDR[11]} {ROLE/m_axi_moMEM_Mp1_ARADDR[12]} {ROLE/m_axi_moMEM_Mp1_ARADDR[13]} {ROLE/m_axi_moMEM_Mp1_ARADDR[14]} {ROLE/m_axi_moMEM_Mp1_ARADDR[15]} {ROLE/m_axi_moMEM_Mp1_ARADDR[16]} {ROLE/m_axi_moMEM_Mp1_ARADDR[17]} {ROLE/m_axi_moMEM_Mp1_ARADDR[18]} {ROLE/m_axi_moMEM_Mp1_ARADDR[19]} {ROLE/m_axi_moMEM_Mp1_ARADDR[20]} {ROLE/m_axi_moMEM_Mp1_ARADDR[21]} {ROLE/m_axi_moMEM_Mp1_ARADDR[22]} {ROLE/m_axi_moMEM_Mp1_ARADDR[23]} {ROLE/m_axi_moMEM_Mp1_ARADDR[24]} {ROLE/m_axi_moMEM_Mp1_ARADDR[25]} {ROLE/m_axi_moMEM_Mp1_ARADDR[26]} {ROLE/m_axi_moMEM_Mp1_ARADDR[27]} {ROLE/m_axi_moMEM_Mp1_ARADDR[28]} {ROLE/m_axi_moMEM_Mp1_ARADDR[29]} {ROLE/m_axi_moMEM_Mp1_ARADDR[30]} {ROLE/m_axi_moMEM_Mp1_ARADDR[31]} {ROLE/m_axi_moMEM_Mp1_ARADDR[32]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ROLE/m_axi_moMEM_Mp1_AWSIZE[0]} {ROLE/m_axi_moMEM_Mp1_AWSIZE[1]} {ROLE/m_axi_moMEM_Mp1_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 33 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ROLE/m_axi_moMEM_Mp1_AWADDR[0]} {ROLE/m_axi_moMEM_Mp1_AWADDR[1]} {ROLE/m_axi_moMEM_Mp1_AWADDR[2]} {ROLE/m_axi_moMEM_Mp1_AWADDR[3]} {ROLE/m_axi_moMEM_Mp1_AWADDR[4]} {ROLE/m_axi_moMEM_Mp1_AWADDR[5]} {ROLE/m_axi_moMEM_Mp1_AWADDR[6]} {ROLE/m_axi_moMEM_Mp1_AWADDR[7]} {ROLE/m_axi_moMEM_Mp1_AWADDR[8]} {ROLE/m_axi_moMEM_Mp1_AWADDR[9]} {ROLE/m_axi_moMEM_Mp1_AWADDR[10]} {ROLE/m_axi_moMEM_Mp1_AWADDR[11]} {ROLE/m_axi_moMEM_Mp1_AWADDR[12]} {ROLE/m_axi_moMEM_Mp1_AWADDR[13]} {ROLE/m_axi_moMEM_Mp1_AWADDR[14]} {ROLE/m_axi_moMEM_Mp1_AWADDR[15]} {ROLE/m_axi_moMEM_Mp1_AWADDR[16]} {ROLE/m_axi_moMEM_Mp1_AWADDR[17]} {ROLE/m_axi_moMEM_Mp1_AWADDR[18]} {ROLE/m_axi_moMEM_Mp1_AWADDR[19]} {ROLE/m_axi_moMEM_Mp1_AWADDR[20]} {ROLE/m_axi_moMEM_Mp1_AWADDR[21]} {ROLE/m_axi_moMEM_Mp1_AWADDR[22]} {ROLE/m_axi_moMEM_Mp1_AWADDR[23]} {ROLE/m_axi_moMEM_Mp1_AWADDR[24]} {ROLE/m_axi_moMEM_Mp1_AWADDR[25]} {ROLE/m_axi_moMEM_Mp1_AWADDR[26]} {ROLE/m_axi_moMEM_Mp1_AWADDR[27]} {ROLE/m_axi_moMEM_Mp1_AWADDR[28]} {ROLE/m_axi_moMEM_Mp1_AWADDR[29]} {ROLE/m_axi_moMEM_Mp1_AWADDR[30]} {ROLE/m_axi_moMEM_Mp1_AWADDR[31]} {ROLE/m_axi_moMEM_Mp1_AWADDR[32]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {ROLE/rp_ROLE_miROL_Mem_Mp1_ARREADY[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {ROLE/rp_ROLE_miROL_Mem_Mp1_AWREADY[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {ROLE/rp_ROLE_miROL_Mem_Mp1_RVALID[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {ROLE/rp_ROLE_miROL_Mem_Mp1_WREADY[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 33 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {ROLE/soMemWrCmdP0_TDATA[0]} {ROLE/soMemWrCmdP0_TDATA[32]} {ROLE/soMemWrCmdP0_TDATA[33]} {ROLE/soMemWrCmdP0_TDATA[34]} {ROLE/soMemWrCmdP0_TDATA[35]} {ROLE/soMemWrCmdP0_TDATA[36]} {ROLE/soMemWrCmdP0_TDATA[37]} {ROLE/soMemWrCmdP0_TDATA[38]} {ROLE/soMemWrCmdP0_TDATA[39]} {ROLE/soMemWrCmdP0_TDATA[40]} {ROLE/soMemWrCmdP0_TDATA[41]} {ROLE/soMemWrCmdP0_TDATA[42]} {ROLE/soMemWrCmdP0_TDATA[43]} {ROLE/soMemWrCmdP0_TDATA[44]} {ROLE/soMemWrCmdP0_TDATA[45]} {ROLE/soMemWrCmdP0_TDATA[46]} {ROLE/soMemWrCmdP0_TDATA[47]} {ROLE/soMemWrCmdP0_TDATA[48]} {ROLE/soMemWrCmdP0_TDATA[49]} {ROLE/soMemWrCmdP0_TDATA[50]} {ROLE/soMemWrCmdP0_TDATA[51]} {ROLE/soMemWrCmdP0_TDATA[52]} {ROLE/soMemWrCmdP0_TDATA[53]} {ROLE/soMemWrCmdP0_TDATA[54]} {ROLE/soMemWrCmdP0_TDATA[55]} {ROLE/soMemWrCmdP0_TDATA[56]} {ROLE/soMemWrCmdP0_TDATA[57]} {ROLE/soMemWrCmdP0_TDATA[58]} {ROLE/soMemWrCmdP0_TDATA[59]} {ROLE/soMemWrCmdP0_TDATA[60]} {ROLE/soMemWrCmdP0_TDATA[61]} {ROLE/soMemWrCmdP0_TDATA[62]} {ROLE/soMemWrCmdP0_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {ROLE/rp_ROLE_siROL_Mem_Mp0_WrCmd_tready[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {ROLE/rp_ROLE_siROL_Mem_Mp0_Write_tready[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[0]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[1]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[2]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[3]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[4]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[5]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[6]} {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {ROLE/rp_ROLE_soROL_Mem_Mp0_WrSts_tvalid[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {ROLE/soMemWriteP0_TKEEP[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {ROLE/soMemWriteP0_TLAST[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 8 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {ROLE/UAF/siMemWrStsP0_TDATA[0]} {ROLE/UAF/siMemWrStsP0_TDATA[1]} {ROLE/UAF/siMemWrStsP0_TDATA[2]} {ROLE/UAF/siMemWrStsP0_TDATA[3]} {ROLE/UAF/siMemWrStsP0_TDATA[4]} {ROLE/UAF/siMemWrStsP0_TDATA[5]} {ROLE/UAF/siMemWrStsP0_TDATA[6]} {ROLE/UAF/siMemWrStsP0_TDATA[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/enqueueFSM_reg[1]_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/image_loaded_reg_n_3_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list ROLE/m_axi_moMEM_Mp1_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list ROLE/m_axi_moMEM_Mp1_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list ROLE/m_axi_moMEM_Mp1_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list ROLE/m_axi_moMEM_Mp1_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list ROLE/m_axi_moMEM_Mp1_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[18]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[20]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[22]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[24]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
connect_debug_port u_ila_0/probe53 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
connect_debug_port u_ila_0/probe54 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
connect_debug_port u_ila_0/probe55 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
connect_debug_port u_ila_0/probe56 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
connect_debug_port u_ila_0/probe57 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[30]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
connect_debug_port u_ila_0/probe58 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/processed_bytes_rx_reg_n_3_[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
connect_debug_port u_ila_0/probe59 [get_nets [list ROLE/UAF/U0/Block_codeRepl141_pr_U0/ready_to_accept_new_4_reg_1166]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
connect_debug_port u_ila_0/probe60 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/signal_init[0]_i_2_n_3}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
connect_debug_port u_ila_0/probe61 [get_nets [list ROLE/siMemWrStsP0_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
connect_debug_port u_ila_0/probe62 [get_nets [list ROLE/UAF/siMemWrStsP0_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
connect_debug_port u_ila_0/probe63 [get_nets [list ROLE/UAF/U0/Block_codeRepl141_pr_U0/skip_read]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
connect_debug_port u_ila_0/probe64 [get_nets [list ROLE/UAF/soMemWrCmdP0_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe65]
set_property port_width 1 [get_debug_ports u_ila_0/probe65]
connect_debug_port u_ila_0/probe65 [get_nets [list ROLE/soMemWrCmdP0_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe66]
set_property port_width 1 [get_debug_ports u_ila_0/probe66]
connect_debug_port u_ila_0/probe66 [get_nets [list ROLE/UAF/soMemWriteP0_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe67]
set_property port_width 1 [get_debug_ports u_ila_0/probe67]
connect_debug_port u_ila_0/probe67 [get_nets [list ROLE/soMemWriteP0_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe68]
set_property port_width 1 [get_debug_ports u_ila_0/probe68]
connect_debug_port u_ila_0/probe68 [get_nets [list ROLE/UAF/U0/Block_codeRepl141_pr_U0/timeoutCnt_V]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe69]
set_property port_width 1 [get_debug_ports u_ila_0/probe69]
connect_debug_port u_ila_0/probe69 [get_nets [list {ROLE/UAF/U0/Block_codeRepl141_pr_U0/img_in_axi_stream_V_1_fifo_U/write_chunk_to_ddr_p_reg[0]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
