set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[7]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_3_empty_n]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_3_full_n]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_3_empty_n]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[33]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[37]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[35]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[41]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[39]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[45]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[43]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[47]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[51]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[55]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[59]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[63]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[61]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[57]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[53]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[49]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[13]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_3_full_n]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[34]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[32]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[38]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[36]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[42]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[40]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[46]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[44]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[48]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[52]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[56]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[60]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[62]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[58]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[54]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[50]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[14]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/pRXPathDDR_U0_sImageLoaded_V_write]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/sImageLoaded_V_dout]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/sImageLoaded_V_full_n]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/sImageLoaded_V_empty_n]
set_property MARK_DEBUG true [get_nets ROLE/UAF/U0/pProcPath_U0_sImageLoaded_V_read]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pTXPath_U0/dequeueFSM[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pTXPath_U0/dequeueFSM[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/HarrisFSM[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/HarrisFSM[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/HarrisFSM[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[17]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[28]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[31]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[26]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[27]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[16]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[29]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[30]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[25]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[22]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[24]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[18]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[20]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[14]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[15]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[21]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[19]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[8]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[9]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[10]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[12]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[13]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[11]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[3]}]
set_property MARK_DEBUG true [get_nets ROLE/soMemWrCmdP0_TVALID]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[39]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {ROLE/soMemWrCmdP0_TDATA[54]}]
set_property MARK_DEBUG true [get_nets ROLE/UAF/soMemWrCmdP0_TREADY]
set_property MARK_DEBUG true [get_nets ROLE/UAF/siMemWrStsP0_TVALID]
set_property MARK_DEBUG true [get_nets ROLE/siMemWrStsP0_TREADY]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/siMemWrStsP0_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/pRXPathDDR_U0/ddr_addr_in_reg[0]_0}]
set_property MARK_DEBUG true [get_nets {ROLE/UAF/U0/sRxtoTx_Meta_V_tkeep_U/ddr_addr_in_reg[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list SHELL/SuperCfg.ETH0/ETH/CORE/IP/inst/xpcs/inst/ten_gig_eth_pcs_pma_shared_clock_reset_block/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[0]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[1]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[2]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[3]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[4]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[5]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[6]} {ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_1_fifo_U/U_fifo_w8_d65_A_shiftReg/img_in_axi_stream_V_1_din[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[0]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[1]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[2]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[3]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[4]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[5]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[6]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[7]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[8]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[9]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[10]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[11]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[12]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[13]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[14]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[15]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[16]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[17]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[18]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[19]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[20]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[21]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[22]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[23]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[24]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[25]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[26]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[27]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[28]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[29]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[30]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[31]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[32]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[33]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[34]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[35]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[36]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[37]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[38]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[39]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[40]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[41]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[42]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[43]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[44]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[45]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[46]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[47]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[48]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[49]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[50]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[51]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[52]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[53]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[54]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[55]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[56]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[57]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[58]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[59]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[60]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[61]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[62]} {ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_1_dout[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[0]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[1]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[2]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[3]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[4]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[5]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[6]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[7]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[8]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[9]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[10]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[11]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[12]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[13]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[14]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[15]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[16]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[17]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[18]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[19]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[20]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[21]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[22]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[23]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[24]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[25]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[26]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[27]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[28]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[29]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[30]} {ROLE/UAF/U0/pProcPath_U0/cnt_i_load_reg_1487[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ROLE/UAF/U0/pProcPath_U0/HarrisFSM[0]} {ROLE/UAF/U0/pProcPath_U0/HarrisFSM[1]} {ROLE/UAF/U0/pProcPath_U0/HarrisFSM[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ROLE/UAF/U0/pTXPath_U0/dequeueFSM[0]} {ROLE/UAF/U0/pTXPath_U0/dequeueFSM[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[0]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[1]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[2]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[3]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[4]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[5]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[6]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[7]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[8]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[9]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[10]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[11]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[12]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[13]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[14]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[15]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[16]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[17]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[18]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[19]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[20]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[21]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[22]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[23]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[24]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[25]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[26]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[27]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[28]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[29]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[30]} {ROLE/UAF/U0/pProcPath_U0/timeoutCntAbs_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[0]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[1]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[2]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[3]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[4]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[5]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[6]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[7]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[8]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[9]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[10]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[11]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[12]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[13]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[14]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[15]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[16]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[17]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[18]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[19]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[20]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[21]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[22]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[23]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[24]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[25]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[26]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[27]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[28]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[29]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[30]} {ROLE/UAF/U0/pRXPathDDR_U0/processed_bytes_rx_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[0]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[1]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[2]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[3]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[4]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[5]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[6]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[7]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[8]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[9]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[10]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[11]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[12]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[13]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[14]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[15]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[16]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[17]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[18]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[19]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[20]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[21]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[22]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[23]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[24]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[25]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[26]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[27]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[28]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[29]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[30]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_stream_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 5 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[0]} {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[1]} {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[2]} {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[3]} {ROLE/UAF/U0/pRXPathDDR_U0/enqueueFSM[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 31 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[1]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[2]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[3]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[4]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[5]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[6]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[7]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[8]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[9]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[10]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[11]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[12]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[13]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[14]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[15]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[16]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[17]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[18]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[19]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[20]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[21]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[22]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[23]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[24]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[25]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[26]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[27]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[28]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[29]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[30]} {ROLE/UAF/U0/pRXPathDDR_U0/cnt_wr_img_loaded_reg[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 28 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {ROLE/soMemWrCmdP0_TDATA[0]} {ROLE/soMemWrCmdP0_TDATA[23]} {ROLE/soMemWrCmdP0_TDATA[38]} {ROLE/soMemWrCmdP0_TDATA[39]} {ROLE/soMemWrCmdP0_TDATA[40]} {ROLE/soMemWrCmdP0_TDATA[41]} {ROLE/soMemWrCmdP0_TDATA[42]} {ROLE/soMemWrCmdP0_TDATA[43]} {ROLE/soMemWrCmdP0_TDATA[44]} {ROLE/soMemWrCmdP0_TDATA[45]} {ROLE/soMemWrCmdP0_TDATA[46]} {ROLE/soMemWrCmdP0_TDATA[47]} {ROLE/soMemWrCmdP0_TDATA[48]} {ROLE/soMemWrCmdP0_TDATA[49]} {ROLE/soMemWrCmdP0_TDATA[50]} {ROLE/soMemWrCmdP0_TDATA[51]} {ROLE/soMemWrCmdP0_TDATA[52]} {ROLE/soMemWrCmdP0_TDATA[53]} {ROLE/soMemWrCmdP0_TDATA[54]} {ROLE/soMemWrCmdP0_TDATA[55]} {ROLE/soMemWrCmdP0_TDATA[56]} {ROLE/soMemWrCmdP0_TDATA[57]} {ROLE/soMemWrCmdP0_TDATA[58]} {ROLE/soMemWrCmdP0_TDATA[59]} {ROLE/soMemWrCmdP0_TDATA[60]} {ROLE/soMemWrCmdP0_TDATA[61]} {ROLE/soMemWrCmdP0_TDATA[62]} {ROLE/soMemWrCmdP0_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {ROLE/UAF/siMemWrStsP0_TDATA[0]} {ROLE/UAF/siMemWrStsP0_TDATA[1]} {ROLE/UAF/siMemWrStsP0_TDATA[2]} {ROLE/UAF/siMemWrStsP0_TDATA[3]} {ROLE/UAF/siMemWrStsP0_TDATA[4]} {ROLE/UAF/siMemWrStsP0_TDATA[5]} {ROLE/UAF/siMemWrStsP0_TDATA[6]} {ROLE/UAF/siMemWrStsP0_TDATA[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[18]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[20]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[22]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[24]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[30]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/cnt_rd_stream_reg_n_1_[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {ROLE/UAF/U0/sRxtoTx_Meta_V_tkeep_U/ddr_addr_in_reg[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {ROLE/UAF/U0/pRXPathDDR_U0/ddr_addr_in_reg[0]_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_3_empty_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list ROLE/UAF/U0/pRXPathDDR_U0/img_in_axi_stream_V_3_full_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_3_empty_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list ROLE/UAF/U0/pProcPath_U0/img_out_axi_stream_V_3_full_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list ROLE/UAF/U0/pProcPath_U0_sImageLoaded_V_read]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list ROLE/UAF/U0/pRXPathDDR_U0_sImageLoaded_V_write]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list ROLE/UAF/U0/sImageLoaded_V_dout]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list ROLE/UAF/U0/sImageLoaded_V_empty_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list ROLE/UAF/U0/sImageLoaded_V_full_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list ROLE/siMemWrStsP0_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list ROLE/UAF/siMemWrStsP0_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list ROLE/UAF/soMemWrCmdP0_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list ROLE/soMemWrCmdP0_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
