FROM ubuntu:focal

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server sudo build-essential htop iproute2 inetutils-ping -y

RUN apt-get install -y build-essential pkg-config libxml2-dev python3-opencv libjpeg-dev libpng-dev libopencv-dev libopencv-contrib-dev rename rpl dialog cmake swig python3-dev python3.8-venv gcc-multilib
RUN apt-get install -y libjpeg62

RUN apt-get install -y cmake git libtiff-dev libgtk-3-dev libavcodec-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev libjpeg-dev libatlas-base-dev python3-numpy libtbb2 libtbb-dev libdc1394-22-dev libopenexr-dev
RUN mkdir /opencv_build
WORKDIR /opencv_build
RUN git clone https://github.com/opencv/opencv.git 
RUN git clone https://github.com/opencv/opencv_contrib.git
RUN cd /opencv_build/opencv; mkdir -p build && cd build; cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D OPENCV_GENERATE_PKGCONFIG=ON -D OPENCV_EXTRA_MODULES_PATH=/opencv_build/opencv_contrib/modules -D INSTALL_C_EXAMPLES=ON  ..; make -j$(nproc); make install


RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test 

RUN  echo 'test:test' | chpasswd

RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN service ssh start

EXPOSE 22
EXPOSE 2718-2750/udp
EXPOSE 2718-2750/tcp

WORKDIR /app

ADD srvr_dir /app
RUN chmod +x /app/container_start_srvr.sh

RUN chmod +x /app/warp_transform_srvr_cpu && chmod +x /app/setup_multisrvr.sh  && chown test -R /app

EXPOSE 2718

#CMD ["/usr/sbin/sshd","-D"]
USER test
CMD ["/app/container_start_srvr.sh"]

